name: Auto News
on:
  schedule:
    - cron: '0 */6 * * *' # Auto-run every 6 hrs
  workflow_dispatch: # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  with:
    persist-credentials: true
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install tools
      run: pip install requests beautifulsoup4 lxml
    - name: Run Scraper
      run: python scraper.py
    - name: Save changes
  run: |
    git config --global user.name "News Bot"
    git config --global user.email "bot@news.com"
    git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    git add .
    git commit -m "Auto update: $(date +'%d/%m')"
    git push
