name: Auto News Update
on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:

jobs:
  scrape-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install packages
        run: pip install beautifulsoup4 requests
      - name: Run Scraper
        run: python scraper.py
      - name: Commit Changes
        run: |
          git config --global user.name "Auto News Bot"
          git config --global user.email "bot@example.com"
          git add news.csv
          git commit -m "Auto update: $(date +'%d-%m-%Y %H:%M')"
          git push
